<div class="container">
	<h3><?= $this->translate('Přihlášení') ?></h3>

	<div class="row">
		<div class="col-md-6">
			<?= $this->form ?>

			<?php if (isset($this->lostPassword)): ?>
				<div class="alert alert-warning">
					<button class="close" data-dismiss="alert" type="button">×</button>
					Pokud nevíš heslo, nech si <a href="<?= $this->baseUrl($this->translate('ztracene-heslo')) ?>">poslat nové</a> ;)
				</div>
			<?php endif ?>
		</div>

		<div class="col-md-6 text-center">
			<div class="well">
				<h4>Nebo se přihlaš pomocí své oblíbené sociální sítě</h4>
				<br />
				<div>
					<a class="btn btn-danger" href="<?= $this->googleAuthUrl ?>"><i class="fa fa-google-plus"></i>&nbsp; Google</a>
					<a class="btn btn-primary" href="<?= $this->facebookAuthUrl ?>"><i class="fa fa-facebook"></i>&nbsp; Facebook</a>
					<!-- a class="btn btn-info" href="<?= $this->twitterAuthUrl ?>"><i class="fa fa-twitter"></i>&nbsp; Twitter</a -->
				</div>
			</div>
		</div>
	</div>

	<br /><br />

	<div class="text-center well">
		Pokud nemáte účet, můžete si ho <a class="btn btn-info" href="<?= $this->baseUrl($this->translate('vytvoreni-uctu')) ?>">založit zde</a>
	</div>
</div>
